import { device, expect, test } from './helpers'

test.beforeEach(async ({ request }) => { await request.post('/api/dev/reset-admin-locks') })

test('secure chat: create, join with password, messages relay, wrong password fails, wipe on leave', async ({ browser }) => {
  const a = await device(browser, '/chat')
  await a.goto('/chat')
  await a.getByPlaceholder('At least 8 characters').fill('correct horse battery')
  await a.getByRole('button', { name: 'Create secure room' }).click()
  await a.waitForURL(/\/c\/[A-Z0-9]+$/)
  const code = a.url().split('/').pop()!
  await expect(a.getByText(`Room ${code}`)).toBeVisible({ timeout: 15_000 })
  await a.getByPlaceholder('Write a message').fill('secret hello')
  await a.getByRole('button', { name: 'Send' }).click()
  await expect(a.getByText('secret hello')).toBeVisible()

  const b = await device(browser)
  await b.goto(`/c/${code}`)
  await b.getByPlaceholder('Room password').fill('wrong password!!')
  await b.getByRole('button', { name: 'Join chat' }).click()
  await expect(b.getByText('Wrong password')).toBeVisible()
  await b.getByPlaceholder('Room password').fill('correct horse battery')
  await b.getByRole('button', { name: 'Join chat' }).click()
  await expect(b.getByText(`Room ${code}`)).toBeVisible({ timeout: 15_000 })
  await expect(b.getByText('secret hello')).toHaveCount(0)
  await expect(a.getByText('Someone joined')).toBeVisible()
  await expect(b.getByText('2/4 in room')).toBeVisible()
  await a.getByPlaceholder('Write a message').fill('second message')
  await a.getByRole('button', { name: 'Send' }).click()
  await expect(b.getByText('second message')).toBeVisible()
  await b.getByPlaceholder('Write a message').fill('reply!')
  await b.keyboard.press('Enter')
  await expect(a.getByText('reply!')).toBeVisible()

  b.once('dialog', d => d.accept())
  await b.getByRole('button', { name: /Leave/ }).click()
  await expect(a.getByText('Someone left')).toBeVisible()
  const c = await device(browser)
  await c.goto(`/c/${code}`)
  await c.getByPlaceholder('Room password').fill('correct horse battery')
  await c.getByRole('button', { name: 'Join chat' }).click()
  await expect(c.getByText(`Room ${code}`)).toBeVisible({ timeout: 15_000 })
  await expect(c.getByText('second message')).toHaveCount(0)
})

test('public page: publish, view anonymously, edit via token, delete', async ({ browser }) => {
  const a = await device(browser, '/chat')
  await a.goto('/public/new')
  await a.getByPlaceholder('My page').fill('E2E page')
  await a.getByPlaceholder(/Hello/).fill('# Heading\n\nSome **bold** text <script>window.__x=1</script>')
  await a.getByPlaceholder('my-page').fill(`e2e-${Date.now()}`)
  await a.getByRole('button', { name: 'Publish' }).click()
  await expect(a.getByText('Your page is live')).toBeVisible()
  await a.getByRole('link', { name: 'View page' }).click()
  await expect(a.getByRole('heading', { name: 'Heading' })).toBeVisible()
  await expect(a.locator('article strong')).toHaveText('bold')
  expect(await a.evaluate(() => (window as unknown as { __x?: number }).__x)).toBeUndefined()
  await expect(a.locator('meta[name=robots]')).toHaveAttribute('content', /noindex/)
})
