import { randomBytes } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { device, expect, test, twoDevices } from './helpers'

test.beforeEach(async ({ request }) => { await request.post('/api/dev/reset-admin-locks') })

test('settings: found URLs, font, theme and device name persist and apply', async ({ browser }) => {
  const [a, b] = await twoDevices(browser)
  await a.locator('textarea').fill('visit https://example.com and www.example.org')
  await expect(a.getByText('Found URLs')).toBeVisible()
  await a.getByRole('button', { name: 'Settings' }).click()
  await a.getByLabel('Font', { exact: true }).selectOption('mono')
  await a.locator('input[type=range]').fill('24')
  await a.getByLabel('Open URLs in').selectOption('same')
  await a.getByRole('button', { name: 'Save General Settings' }).click()
  await expect(a.getByText('Settings saved')).toBeVisible()
  await a.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  await expect(a.getByRole('link', { name: 'https://example.com' })).toHaveAttribute('target', '_self')
  await expect.poll(() => b.locator('textarea').evaluate(el => getComputedStyle(el).fontSize)).toBe('24px')
  await expect.poll(() => b.locator('textarea').evaluate(el => getComputedStyle(el).fontFamily)).toContain('mono')
  await a.reload()
  await expect.poll(() => a.locator('textarea').evaluate(el => getComputedStyle(el).fontSize)).toBe('24px')

  await a.getByRole('button', { name: 'Settings' }).click()
  await a.getByRole('switch', { name: 'Enable Found URLs' }).click()
  await a.getByRole('button', { name: 'Save General Settings' }).click()
  await a.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  await expect(a.getByRole('button', { name: 'URLs' })).toHaveCount(0)
  await expect(a.getByText('Found URLs')).toHaveCount(0)

  await a.getByRole('button', { name: 'Toggle theme' }).click()
  await expect(a.locator('html')).toHaveClass(/dark/)
  await a.reload()
  await expect(a.locator('html')).toHaveClass(/dark/)
  await expect(b.locator('html')).not.toHaveClass(/dark/)
})

test('text tools: copy, download, clear and the character limit', async ({ browser, context }) => {
  const [a, b] = await twoDevices(browser)
  await a.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await a.locator('textarea').fill('copy me')
  await a.getByRole('button', { name: 'Copy' }).click()
  await expect(a.getByText('Copied')).toBeVisible()
  expect(await a.evaluate(() => navigator.clipboard.readText())).toBe('copy me')
  const dl = a.waitForEvent('download')
  await a.getByRole('button', { name: 'Download text' }).click()
  expect(await readFile(await (await dl).path(), 'utf8')).toBe('copy me')
  await a.locator('textarea').fill('x'.repeat(99_000))
  await expect(a.getByText(/99,000 \/ 100,000/)).toBeVisible()
  await a.locator('textarea').fill('y'.repeat(100_500))
  await expect(a.locator('textarea')).toHaveValue('y'.repeat(100_000))
  a.once('dialog', d => void d.accept())
  await a.getByText('Clear', { exact: true }).click()
  await expect(b.locator('textarea')).toHaveValue('')
  void context
})

test('files: cancel, remove from another device, clear all, and zip everything', async ({ browser }) => {
  const [a, b] = await twoDevices(browser)
  await b.getByRole('button', { name: 'Settings' }).click()
  await b.getByRole('switch', { name: 'Auto-download' }).click()
  await b.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  const files = [['one.txt', 'first file'], ['two.txt', 'second file']] as const
  for (const [name, body] of files) await a.getByTestId('file-input').setInputFiles({ name, mimeType: 'text/plain', buffer: Buffer.from(body) })
  for (const [name] of files) await expect(b.getByTestId(`file-${name}`)).toHaveAttribute('data-status', 'remote', { timeout: 15_000 })
  const big = randomBytes(30 * 1024 * 1024)
  await a.getByTestId('file-input').setInputFiles({ name: 'big.bin', mimeType: 'application/octet-stream', buffer: big })
  const row = b.getByTestId('file-big.bin')
  await expect(row).toHaveAttribute('data-status', 'remote', { timeout: 30_000 })
  await row.getByRole('button', { name: /^Download/ }).click()
  await expect(row).toHaveAttribute('data-status', 'downloading')
  await row.getByRole('button', { name: 'Cancel download' }).click()
  await expect(row).toHaveAttribute('data-status', 'remote')

  await b.getByRole('button', { name: 'Get all' }).click()
  for (const [name] of files) await expect(b.getByTestId(`file-${name}`)).toHaveAttribute('data-status', 'complete', { timeout: 20_000 })
  await b.getByTestId('file-two.txt').getByRole('button', { name: /^Preview/ }).click()
  await expect(b.getByRole('dialog')).toContainText('second file')
  await b.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  const zip = b.waitForEvent('download')
  await b.getByRole('button', { name: 'Zip all' }).click()
  const bytes = await readFile(await (await zip).path())
  expect(bytes.subarray(0, 2).toString()).toBe('PK')
  expect(bytes.includes(Buffer.from('one.txt'))).toBe(true)
  expect(bytes.includes(Buffer.from('first file'))).toBe(true)

  b.once('dialog', d => void d.accept())
  await b.getByTestId('file-one.txt').getByRole('button', { name: /^Remove/ }).click()
  await expect(a.getByTestId('file-one.txt')).toHaveCount(0)
  a.once('dialog', d => void d.accept())
  await a.getByRole('button', { name: 'Remove all files' }).click()
  await expect(b.getByTestId('file-two.txt')).toHaveCount(0)
  await expect(b.getByTestId('file-big.bin')).toHaveCount(0)
  await b.reload()
  await expect(b.getByRole('heading', { name: /^Files/ })).toBeHidden()
})

test('public pages: create, list, edit, edit from another device with the secret link, delete', async ({ browser }) => {
  const a = await device(browser, '/public/new')
  await a.evaluate(() => fetch('/api/dev/reset', { method: 'POST' }))
  await a.reload()
  const slug = `feat-${Date.now()}`
  await a.getByPlaceholder('My page').fill('Original title')
  await a.getByPlaceholder(/Hello/).fill('## Body\n\nOriginal text with **bold**')
  await expect(a.getByLabel('Preview')).toContainText('Original text', { timeout: 5000 })
  await a.getByPlaceholder('my-page').fill(slug)
  await a.getByRole('button', { name: 'Publish' }).click()
  await expect(a.getByText('Your page is live')).toBeVisible()
  await a.getByText('Edit link for other networks').click()
  const editUrl = (await a.locator('details code').innerText()).trim()
  expect(editUrl).toContain(`/public/${slug}/edit?k=`)

  await a.goto('/public')
  await expect(a.getByRole('link', { name: 'Original title' })).toBeVisible()
  await a.getByRole('link', { name: 'Edit', exact: true }).first().click()
  await a.getByPlaceholder('My page').fill('Edited title')
  await a.getByRole('button', { name: 'Save changes' }).click()
  await expect(a.getByRole('heading', { name: 'Edited title' })).toBeVisible()

  const other = await device(browser, new URL(editUrl).pathname + new URL(editUrl).search)
  await expect(other.getByPlaceholder('My page')).toHaveValue('Edited title')
  await other.getByPlaceholder('My page').fill('Edited remotely')
  await other.getByRole('button', { name: 'Save changes' }).click()
  await expect(other.getByRole('heading', { name: 'Edited remotely' })).toBeVisible()

  await a.goto('/public')
  a.once('dialog', d => void d.accept())
  await a.getByRole('button', { name: /^Delete Edited remotely/ }).first().click()
  await expect.poll(async () => (await a.request.get(`/api/p/${slug}`)).status()).toBe(404)
})
