import { createHash, randomBytes } from 'node:crypto'
import { device, expect, test, twoDevices } from './helpers'

test('text typed on one device appears on the other, and URLs are detected', async ({ browser }) => {
  const [a, b] = await twoDevices(browser)
  await expect(b.locator('textarea')).toHaveValue('')
  await a.locator('textarea').fill('hello from A\nhttps://example.com/x')
  await expect(b.locator('textarea')).toHaveValue('hello from A\nhttps://example.com/x')
  await expect(b.getByRole('link', { name: 'https://example.com/x' })).toHaveAttribute('target', '_blank')
  await expect(a.getByText('Saved').first()).toBeVisible()
  await b.reload()
  await expect(b.locator('textarea')).toHaveValue('hello from A\nhttps://example.com/x')
  await b.locator('textarea').fill('reply from B')
  await expect(a.locator('textarea')).toHaveValue('reply from B')
  a.once('dialog', d => d.accept())
  await a.getByText('Clear', { exact: true }).click()
  await expect(b.locator('textarea')).toHaveValue('')
})

test('presence shows both devices and device rename sticks', async ({ browser }) => {
  const [a, b] = await twoDevices(browser)
  await expect(a.getByRole('button', { name: 'Devices online' })).toContainText('2')
  await a.getByRole('button', { name: 'Settings' }).click()
  await a.getByLabel('Device name').fill('Test Laptop')
  await a.getByRole('button', { name: 'Save General Settings' }).click()
  await expect(a.getByText('Settings saved')).toBeVisible()
  await b.getByRole('button', { name: 'Devices online' }).click()
  await expect(b.getByText('Test Laptop')).toBeVisible()
})

test('file is shared peer to peer, verified, and downloadable', async ({ browser }) => {
  const [a, b] = await twoDevices(browser)
  const data = randomBytes(3 * 1024 * 1024 + 12345)
  await a.getByTestId('file-input').setInputFiles({ name: 'blob.bin', mimeType: 'application/octet-stream', buffer: data })
  const rowA = a.getByTestId('file-blob.bin')
  await expect(rowA).toHaveAttribute('data-status', 'complete', { timeout: 20_000 })
  const rowB = b.getByTestId('file-blob.bin')
  await expect(rowB).toBeVisible()
  await expect(rowB).toHaveAttribute('data-status', 'complete', { timeout: 30_000 })
  const dl = b.waitForEvent('download')
  await rowB.getByRole('button', { name: /^Save/ }).click()
  const path = await (await dl).path()
  const got = createHash('sha256').update(await (await import('node:fs/promises')).readFile(path)).digest('hex')
  expect(got).toBe(createHash('sha256').update(data).digest('hex'))
  b.once('dialog', d => d.accept())
  await rowB.getByRole('button', { name: /^Remove/ }).click()
  await expect(rowA).toHaveCount(0)
})

test('a large file can be paused, resumed after reload, and completes', async ({ browser }) => {
  const [a, b] = await twoDevices(browser)
  await b.getByRole('button', { name: 'Settings' }).click()
  await b.getByRole('switch', { name: 'Auto-download' }).click()
  await b.getByRole('button', { name: 'Close' }).click()
  const data = randomBytes(24 * 1024 * 1024)
  await a.getByTestId('file-input').setInputFiles({ name: 'big.bin', mimeType: 'application/octet-stream', buffer: data })
  await expect(a.getByTestId('file-big.bin')).toHaveAttribute('data-status', 'complete', { timeout: 30_000 })
  const row = b.getByTestId('file-big.bin')
  await expect(row).toHaveAttribute('data-status', 'remote')
  await row.getByRole('button', { name: /^Download/ }).click()
  await expect(row).toContainText(/\d+%/, { timeout: 15_000 })
  await row.getByRole('button', { name: 'Pause' }).click().catch(() => undefined)
  await b.reload()
  const row2 = b.getByTestId('file-big.bin')
  await expect(row2).toBeVisible()
  const status = await row2.getAttribute('data-status')
  if (status !== 'complete') await row2.getByRole('button', { name: /Resume|Download/ }).click()
  await expect(row2).toHaveAttribute('data-status', 'complete', { timeout: 60_000 })
})

test('link code from one device is redeemed on another through the link page', async ({ browser }) => {
  const a = await device(browser)
  await a.waitForSelector('textarea')
  await a.evaluate(() => fetch('/api/dev/reset', { method: 'POST' }))
  await a.getByRole('button', { name: 'Settings' }).click()
  await a.getByRole('tab', { name: 'Link Device' }).click()
  await a.getByRole('tab', { name: 'Share Link' }).click()
  const code = (await a.locator('span.size-9, span.size-10').allTextContents()).join('').replace('-', '')
  expect(code).toMatch(/^[0-9A-Z]{8}$/)
  const c = await device(browser, `/link?c=${code}`)
  await c.waitForURL('**/', { timeout: 15_000 })
  await a.getByRole('tab', { name: 'Linked Devices' }).click()
  await expect(a.getByText(/^Linked (just now|\d+ seconds? ago)/).first()).toBeVisible()
  const again = await device(browser, `/link?c=${code}`)
  await expect(again.getByText('Code is invalid or expired')).toBeVisible()
})

test('the sending device can reload mid-transfer: it keeps serving from its stored copy and the download completes', async ({ browser }) => {
  const [a, b] = await twoDevices(browser)
  await b.getByRole('button', { name: 'Settings' }).click()
  await b.getByRole('switch', { name: 'Auto-download' }).click()
  await b.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  const data = randomBytes(40 * 1024 * 1024)
  await a.getByTestId('file-input').setInputFiles({ name: 'holder.bin', mimeType: 'application/octet-stream', buffer: data })
  await expect(a.getByTestId('file-holder.bin')).toHaveAttribute('data-status', 'complete', { timeout: 30_000 })
  await expect(b.getByTestId('file-holder.bin')).toHaveAttribute('data-status', 'remote', { timeout: 30_000 })
  await expect.poll(async () => a.evaluate(async () => { const r = await navigator.storage.getDirectory(); try { const d = await (await r.getDirectoryHandle('files')).getDirectoryHandle((await fetch('/api/files').then(x => x.json()))[0].fileId); await d.getFileHandle('state.json'); return true } catch { return false } }), { timeout: 30_000 }).toBe(true)
  await b.getByTestId('file-holder.bin').getByRole('button', { name: /^Download/ }).click()
  await expect(b.getByTestId('file-holder.bin')).toContainText(/\d+%/, { timeout: 15_000 })
  await a.reload()
  await expect(a.getByTestId('file-holder.bin')).toHaveAttribute('data-status', 'complete', { timeout: 20_000 })
  await expect(b.getByTestId('file-holder.bin')).toHaveAttribute('data-status', 'complete', { timeout: 90_000 })
})
